Hw0212
AlexeyChudinoff/App-Magazin pull request #3
Opened 2024-12-05 06:46 UTC by AlexeyChudinoff

2024-12-05 20:01 UTC, AleksandrZhukovJava requested changes

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/App.java
> +}//App
Можно поставить плагин RainbowBrackets, он цветом подсветит, применение будет похожее

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/product/Article.java
> +  }
Можно просто убрать, работать будет точно так же

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/product/Basket.java
> +  private static Product[] productBasket = new Product[5];
Получается у нас во всех корзинах будут общие товары. Покупатели такой апдейт могут не оценить

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +  private Searchable[] searchable;
final

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +  }
это всё убрать в конструктор

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +  private int id;
название поля не отображает его назначение

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +    if (id == searchable.length) {
безопаснее id >= searchable.length

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +    ArrayList<String> findeProduct = new ArrayList<>();
List<String> findeProduct = new ArrayList<>(); - всегда через абстракцию, без исключений

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +    }
а почему бы сразу не печатать? все в одном цикле

2024-12-05 20:01 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +      }
это будет не нужно если убрать инициализацию в конструктор

2024-12-06 09:04 UTC, AlexeyChudinoff commented on src/org/skypro/skyshop/product/Basket.java
> +  private static Product[] productBasket = new Product[5];
:)

2024-12-07 07:51 UTC, AlexeyChudinoff commented on src/org/skypro/skyshop/App.java
> +}//App
я пытался, но похоже санкции ...."но в настоящее время мы не можем предоставлять вам наши продукты или услуги из-за правил экспортного контроля."

2024-12-07 08:39 UTC, AlexeyChudinoff commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +    if (id == searchable.length) {
не могу уловить, как в этом контексте можно использовать условие больше или равно длине массива ? в чём тут безопасность ? я проверяю каждый элемент свободно место или нет. если свободно, записываю свой, если занят, вывожу что не возможно.

2024-12-08 16:39 UTC, AlexeyChudinoff commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +    ArrayList<String> findeProduct = new ArrayList<>();
это замечание мне не понятно, я думал, что реализую абстракцию через то, что в main скрываю как реализовывается тот или иной метод, а тут ? в чём тут абстракция ?

2024-12-12 14:28 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +    if (id == searchable.length) {
Если вкратце, это просто хороший паттерн на будущее, на 4 курсе ты изучишь ситуации в которых тут id может проскочить отметку и стать больше длинны массива, в таком случае мы просто будем ловить не бизнесовые ошибки, поэтому >= безопаснее, тк как покрывает и твою ситуацию и остальные. В рамках этого задания это работает, но я посчитал что учится сразу верным алгоритмам построения кода важнее
В целом тут вообще можно перевернуть условие на if (id < searchable.length) с соответствующими имениями

2024-12-12 14:28 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/searchProduct/SearchEngine.java
> +    ArrayList<String> findeProduct = new ArrayList<>();
Ты создаешь конкретный объект ArrayList, если далее тебе нужно будет выполнить скажем операцию findeProduct = new LinkedList<>() ты этого сделать уже не сможешь.
Вся суть полиморфизма Java - использование абстракций что бы получить гибкость в инициализации объектов. 
При объявлении 
`ArrayList<String> findeProduct = new ArrayList<>();`
у тебя нет выбора, только 1 инициализация 
При объявлении
`Collection<String> findeProduct = new ArrayList<>();`
мы получаем возможность использовать любую коллекцию в дальнейшем, собрать лист из разных коллекций, передавать в методы разные коллекции, и много чего еще
Всегда объявляй лист как минимум так 
`List<String> findeProduct = new ArrayList<>();`

2024-12-14 15:30 UTC, merged